import { TsIcon } from "@/components/ui/TSIcon";
import type { PersonalConfig } from "@/types";
import {
	RiCss3Fill,
	RiDatabaseFill,
	RiGitPullRequestFill,
	RiGithubFill,
	RiGitlabFill,
	RiJavaFill,
	RiJavascriptFill,
	RiPhpFill,
	RiQuillPenAiFill,
	RiQuillPenAiLine,
	RiReactjsFill,
	RiReactjsLine,
	RiServerLine,
	RiStackLine,
	RiTailwindCssFill,
	RiVuejsFill,
	RiWordpressFill,
} from "@remixicon/react";
import dayjs from "dayjs";
import { DockerIcon } from "./components/ui/docker-icon";
import { PythonIcon } from "./components/ui/python-icon";

export const config: PersonalConfig = {
	name: "Haitham Alathamneh",
	role: "Frontend Engineer",
	seniority: "Senior",
	profile:
		"A skilled web developer with over seven years of expertise, primarily in React and modern frontend technologies, along with solid backend experience. I hold a Blue Card, enabling me to work across Europe.",
	links: {
		github: "https://github.com/hathamneh",
		linkedin: "https://www.linkedin.com/in/hathamneh/",
		facebook: "https://www.facebook.com/himo.athamneh/",
	},
	experience: [
		{
			title: "Senior Fullstack Engineer (Part-time)",
			from: dayjs("2022-06-01"),
			isCurrent: true,
			company: "Monbits",
			location: "Remote",
			achievements:
				"At Monbits, I developed real-time wizards for currency trading, architected micro-services connecting the main app to external APIs, implemented RESTful APIs across multiple frontends, integrated payment services, created a reusable UI component library, and contributed to Flutter mobile app development.",
			skills: [
				{ name: "React", icon: <RiReactjsFill /> },
				{ name: "Vue.js", icon: <RiVuejsFill /> },
				"Bun",
				"Remix",
				"Nuxt.js",
				{ name: "Typescript", icon: <TsIcon /> },
				{ name: "Docker", icon: <DockerIcon /> },
				{ name: "Tailwind CSS", icon: <RiTailwindCssFill /> },
				"PostgreSQL",
				"Redis",
				"Elysia.js",
				"Kubernetes",
				"Flutter",
			],
		},
		{
			title: "Senior AI Frontend Engineer",
			from: dayjs("2025-03-01"),
			to: dayjs("2025-04-08"),
			company: "Aleph Alpha GmbH.",
			location: "Heidelberg, Germany",
			achievements:
				"During my brief yet impactful tenure at Aleph Alpha, I developed proof-of-concept applications for potential enterprise clients interested in AI solutions. Additionally, I created a comprehensive library of reusable UI components that significantly accelerated the development process of POCs, enabling faster delivery and more polished demonstrations for stakeholders.",
			skills: [
				{ name: "Vue.js", icon: <RiVuejsFill /> },
				{ name: "Typescript", icon: <TsIcon /> },
				{ name: "Tailwind CSS", icon: <RiTailwindCssFill /> },
				{ name: "Docker", icon: <DockerIcon /> },
				{ name: "Python", icon: <PythonIcon /> },
			],
		},
		{
			title: "Senior Frontend Engineer",
			from: dayjs("2020-04-01"),
			to: dayjs("2025-02-28"),
			company: "Power Factors Inc",
			location: "Munich, Germany",
			achievements:
				"During my tenure, I engineered a robust reporting engine with 15 extensible widgets and led a complete refactoring of all 14 product modules from legacy HTML/jQuery to a modern React Single Page Application. I established and managed Docker images for Frontend builds in both production and development environments. Additionally, I modernized the build process by upgrading from Webpack 4 to Vite, and strengthened quality assurance by implementing numerous E2E tests using Playwright.",
			skills: [
				{ name: "React", icon: <RiReactjsFill /> },
				{ name: "Typescript", icon: <TsIcon /> },
				{ name: "Javascript", icon: <RiJavascriptFill /> },
				{ name: "Docker", icon: <DockerIcon /> },
				"CI/CD",
				{ name: "Python", icon: <PythonIcon /> },
				"Django",
				"Playwright",
				"Vite",
			],
		},
		{
			title: "Frontend Software Engineer",
			from: dayjs("2017-09-01"),
			to: dayjs("2020-04-01"),
			company: "Wiley",
			location: "Amman, Jordan",
			achievements:
				"During my time at Wiley, I implemented an advanced E-Reader capable of reading EPUBs and PDFs online, built multiple journals and online magazines using an in-house JS framework with PUG and SASS, and upgraded the build process from gulp tasks to Webpack.",
			skills: [
				{ name: "Javascript", icon: <RiJavascriptFill /> },
				{ name: "Sass/SCSS", icon: <RiCss3Fill /> },
				"Pug (Jade)",
				{ name: "Java", icon: <RiJavaFill /> },
				"Webpack",
			],
		},
		{
			title: "Fullstack Engineer",
			from: dayjs("2015-09-01"),
			to: dayjs("2019-05-01"),
			company: "Freelance",
			location: "Amman, Jordan",
			achievements:
				"As a freelance engineer, I developed a comprehensive delivery system for package and courier management, created a web store featuring linked inventory management for merchandise tracking, and collaborated with startups to build their front-page websites and blogs.",
			skills: [
				{ name: "PHP", icon: <RiPhpFill /> },
				{ name: "Laravel" },
				{ name: "Wordpress", icon: <RiWordpressFill /> },
				{ name: "Vuejs", icon: <RiVuejsFill /> },
				{ name: "React", icon: <RiReactjsFill /> },
			],
		},
	],
	education: [
		{
			title: "B.Sc in Computer Engineering",
			from: dayjs("2013-09-01"),
			to: dayjs("2018-06-01"),
			company: "University of Jordan",
			location: "Amman, Jordan",
			skills: [
				"Networks",
				"Data Communication",
				"Micro-electronics",
				"Embedded Systems",
				"Compilers",
				"OS",
				"Assembly",
				"Parallel Programming",
				"Java",
				"C/C++",
				"Algorithm Design",
				"Data Structures",
			],
		},
	],
	skills: [
		{ name: "Docker", icon: <DockerIcon /> },
		{ name: "React", icon: <RiReactjsFill /> },
		{ name: "Typescript", icon: <TsIcon /> },
		{ name: "Javascript", icon: <RiJavascriptFill /> },
		"CI/CD",
		"Laravel",
		{ name: "Git", icon: <RiGitPullRequestFill /> },
		{ name: "GitLab CI", icon: <RiGitlabFill /> },
		{ name: "GitHub Actions", icon: <RiGithubFill /> },
		{ name: "UI/UX", icon: <RiQuillPenAiFill /> },
		"RESTful APIs",
		{ name: "Databases", icon: <RiDatabaseFill /> },
		"Kubernetes",
		"Redis",
		"Bun",
		"Next.js",
		"Remix",
		"BullMQ",
		"Elysia.js",
		"AWS",
	],
	services: [
		{
			icon: <RiReactjsLine />,
			title: "Frontend Development",
			description:
				"I specialize in building responsive and user-friendly websites using modern web technologies.",
		},
		{
			icon: <RiServerLine />,
			title: "Backend Development",
			description:
				"I specialize in building scalable and efficient backend systems using modern web technologies.",
		},
		{
			icon: <RiStackLine />,
			title: "Fullstack Development",
			description:
				"I specialize in building fullstack applications using modern web technologies.",
		},
		{
			icon: <RiQuillPenAiLine />,
			title: "UI/UX Design",
			description:
				"I specialize in designing user-friendly interfaces and experiences using modern design tools.",
		},
	],
	projects: [
		{
			id: "monease",
			image: "monease.png",
			category: ["Web App"],
			title: "Monease.io",
			description:
				"A versatile money and crypto exchange platform available as a Private-label PaaS, developed by a team of three developers. Built with Remix on the frontend and Bun/Elysia.js on the backend, utilizing Prisma ORM with PostgreSQL, BullMQ for background jobs, and containerized with Docker for Kubernetes deployments.",
			url: "https://monease.io",
			stack: [
				{ name: "React", icon: <RiReactjsFill /> },
				{ name: "Typescript", icon: <TsIcon /> },
				{ name: "Docker", icon: <DockerIcon /> },
				"Remix",
				{ name: "Tailwind CSS", icon: <RiTailwindCssFill /> },
				"Bun",
				"PostgreSQL",
				"Elysia.js",
				"Redis",
				"Kubernetes",
			],
		},
		{
			id: "wird",
			image: "wird.png",
			category: ["Web App"],
			title: "Wird Contests",
			description:
				"Wird is a non-profitable platform which will assist teachers in creating personalized contests for their students. The public pages are built with Next.js, a React framework for building server-side rendered applications. And the web application frontend is built with create-react-app and React-Router. The backend is a python django REST API.",
			url: "https://wird.app",
			stack: [
				{ name: "React", icon: <RiReactjsFill /> },
				{ name: "Typescript", icon: <TsIcon /> },
				"Next.js",
				{ name: "Tailwind CSS", icon: <RiTailwindCssFill /> },
				"react-router",
				{ name: "Python", icon: <PythonIcon /> },
				"Django",
			],
		},
		{
			id: "qudsinfo",
			image: "qudsinfo.png",
			category: ["CMS"],
			title: "Qudsinfo.com",
			description:
				"A knowledge base website about Jerusalem, featuring a customized Wordpress with Vue.js template, interactive map, and a public API, optimized for performance using Memcached. The platform hosts extensive articles and information accessible through a user-friendly interface.",
			url: "https://qudsinfo.com",
			stack: [
				{ name: "Wordpress", icon: <RiWordpressFill /> },
				{ name: "Javascript", icon: <RiJavascriptFill /> },
				{ name: "PHP", icon: <RiPhpFill /> },
				{ name: "Vue.js", icon: <RiVuejsFill /> },
				"Webpack",
				"WP Plugins",
				"S3",
				"AWS CloudFront",
			],
		},
		{
			id: "wiley",
			image: "wiley.png",
			category: ["Journal"],
			title: "Wiley Online Library",
			description:
				"During my work at Wiley, I contributed to the development of Wiley Online Library, enhancing user experience and improving search functionality. I also worked on the eReader feature, which allows users to read PDF and EPUB files online.",
			url: "https://onlinelibrary.wiley.com",
			stack: [
				{ name: "Javascript", icon: <RiJavascriptFill /> },
				{ name: "Sass/SCSS", icon: <RiCss3Fill /> },
				"Pug (Jade)",
				{ name: "Java", icon: <RiJavaFill /> },
				"Webpack",
			],
		},
		{
			id: "delivery-system",
			image: "shipment-tracking.webp",
			title: "Delivery System",
			category: ["Web App"],
			description:
				"A comprehensive delivery management system designed for courier service companies, featuring shipment tracking, courier management, reporting, and invoicing capabilities. Built with PHP Laravel and Blade templates, utilizing MySQL database. The mobile-responsive design allows couriers to efficiently update delivery statuses and manage tasks while on the move.",
			url: "https://github.com/hathamneh/delivery-system",
			stack: [
				"Laravel",
				{ name: "PHP", icon: <RiPhpFill /> },
				{ name: "Javascript", icon: <RiJavascriptFill /> },
				"Blade",
			],
		},
	],
	languages: [
		{
			name: "English",
			level: "Fluent",
			percentage: 100,
		},
		{
			name: "Arabic",
			level: "Native",
			percentage: 100,
		},
		{
			name: "German",
			level: "Basic",
			percentage: 25,
		},
	],
};
